// <auto-generated />
namespace Truyum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TruyumContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TruyumContext));
        
        string IMigrationMetadata.Id
        {
            get { return "202102182015383_Truyum Context"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
